"""
BeamerAgent: generates a concise XeLaTeX Beamer presentation summarizing
simulation results at the end of each pipeline run.
"""

import re
import subprocess
from pathlib import Path
from datetime import datetime

import sys; sys.path.insert(0, ".")
from src.agents.base import BaseAgent
from state import SimState


def _parse_complexes(phr_path: Path) -> list[dict]:
    """Extract metal complex reactions and log_k values from .phr file."""
    complexes = []
    if not phr_path.exists():
        return complexes
    text = phr_path.read_text()
    # Match reaction lines followed by log_k
    rxn_pattern = re.compile(
        r"^([A-Za-z]+\+\d.*?=\s*\S+)\s*\n\s*log_k\s+([-\d.]+)",
        re.MULTILINE,
    )
    for m in rxn_pattern.finditer(text):
        rxn  = m.group(1).strip()
        logk = float(m.group(2))
        # Extract product name (last token after '=')
        product = rxn.split("=")[-1].strip()
        complexes.append({"reaction": rxn, "product": product, "log_k": logk})
    return complexes


def _scorecard_rows(scorecard: dict, equiv_pts: list, target_metals: list,
                    impurity_metals: list) -> str:
    """Build LaTeX table rows for the scorecard slide."""
    rows = []
    role_order = target_metals + impurity_metals
    for metal in role_order:
        s = scorecard.get(metal)
        if not s:
            continue
        role = "Target" if metal in target_metals else "Impurity"
        vals = " & ".join(
            f"{s.get(f'pct_at_{eq}_equiv', 0):.0f}\\%"
            for eq in equiv_pts
        )
        rmse = s.get("rmse")
        rmse_str = f"{rmse:.1f}" if rmse is not None else "--"
        score = s.get("score", 0)
        max_s = s.get("max_score", 2)
        result_map = {
            "target":   {2: r"\textcolor{green!60!black}{Protected}",
                         1: r"\textcolor{orange}{Partial}",
                         0: r"\textcolor{red}{Lost}"},
            "impurity": {2: r"\textcolor{green!60!black}{Removed}",
                         1: r"\textcolor{orange}{Partial}",
                         0: r"\textcolor{red}{Stays}"},
        }
        role_key = "target" if metal in target_metals else "impurity"
        result = result_map[role_key].get(score, "--")
        rows.append(
            f"    {metal} & {role} & {vals} & {rmse_str} & {result} \\\\"
        )
    return "\n".join(rows)


def _logk_table_rows(complexes: list) -> str:
    rows = []
    for c in complexes:
        lk = c["log_k"]
        if lk == -999:
            continue
        # Escape special chars for LaTeX
        prod = c["product"].replace("_", r"\_")
        rxn  = c["reaction"].replace("_", r"\_").replace("+", "$^{+}$", 1)
        rows.append(f"    {prod} & {lk:.2f} \\\\")
    return "\n".join(rows)


def _build_tex(modifier: str, slug: str, scorecard: dict, figure_path: str,
               sp_path: str, complexes: list, equiv_pts: list,
               exp_cfg: dict, cfg: dict) -> str:

    target_metals   = cfg["analyst"].get("target_metals",   ["Cu","Co","Ni","Mn"])
    impurity_metals = cfg["analyst"].get("impurity_metals", ["Al","Fe"])
    date_str = datetime.utcnow().strftime("%Y-%m-%d")

    # Bare filenames — \graphicspath{figures/} resolves the subdir on both
    # local xelatex and Overleaf (upload figures to the figures/ subfolder)
    fig_main = Path(figure_path).name if figure_path else ""
    fig_sp   = Path(sp_path).name     if sp_path     else ""

    sc_rows   = _scorecard_rows(scorecard, equiv_pts, target_metals, impurity_metals)
    lk_rows   = _logk_table_rows(complexes)
    equiv_hdrs = " & ".join(f"@ {eq} eq" for eq in equiv_pts)

    # Header columns for scorecard
    n_equiv = len(equiv_pts)
    col_spec = "lll" + "r" * n_equiv + "rr"

    tex = rf"""% !TEX program = xelatex
% Auto-generated by BeamerAgent — {date_str}
\documentclass[8pt,aspectratio=169]{{beamer}}

\usetheme[numbering=fraction,progressbar=frametitle]{{metropolis}}
\usepackage{{fontspec}}
\setmainfont{{Times New Roman}}
\usepackage{{booktabs}}
\usepackage{{graphicx}}
\graphicspath{{{{figures/}}}}
\usepackage{{xcolor}}
\usepackage{{array}}
\usepackage{{colortbl}}

\definecolor{{mblue}}{{RGB}}{{0,82,147}}
\definecolor{{mgray}}{{RGB}}{{245,245,245}}

\title{{Thermodynamic Modeling: {modifier}}}
\subtitle{{NMC532 Leachate, Modifier 0.20 mol/kgw}}
\author{{MDPSA Pipeline}}
\date{{{date_str}}}
\institute{{NRCan CC-NRCan-078}}

\begin{{document}}

\maketitle

%% ── Slide 1: Model vs Experiment ─────────────────────────────────────────────
\begin{{frame}}{{Model vs. Experiment}}
  \begin{{center}}
"""
    if fig_main:
        tex += rf"""    \includegraphics[width=0.92\textwidth,height=0.82\textheight,keepaspectratio]{{{fig_main}}}
"""
    else:
        tex += "    \\textit{Figure not available}\n"

    tex += r"""  \end{center}
\end{frame}

%% ── Slide 2: Species Contributions ──────────────────────────────────────────
\begin{frame}{Species Contributions (Open System)}
  \begin{center}
"""
    if fig_sp:
        tex += rf"""    \includegraphics[width=0.92\textwidth,height=0.82\textheight,keepaspectratio]{{{fig_sp}}}
"""
    else:
        tex += "    \\textit{Figure not available}\n"

    tex += r"""  \end{center}
\end{frame}

"""

    tex += rf"""%% ── Slide 3: Selectivity Scorecard ──────────────────────────────────────────
\begin{{frame}}{{Selectivity Scorecard}}
  \vspace{{2pt}}
  \begin{{center}}
  \small
  \setlength{{\tabcolsep}}{{5pt}}
  \renewcommand{{\arraystretch}}{{1.3}}
  \begin{{tabular}}{{{col_spec}}}
    \toprule
    \textbf{{Metal}} & \textbf{{Role}} & {equiv_hdrs} & \textbf{{RMSE (pp)}} & \textbf{{Verdict}} \\
    \midrule
{sc_rows}
    \bottomrule
  \end{{tabular}}
  \end{{center}}
  \vspace{{4pt}}
  \begin{{beamercolorbox}}[rounded=true, shadow=false, wd=\textwidth]{{block body}}
    \tiny
    RMSE: root-mean-square error in percentage points vs. experiment (CC-NRCan-078). \\
    Protected/Removed: model matches experiment at all comparison equiv points.
  \end{{beamercolorbox}}
\end{{frame}}

%% ── Slide 4: Thermodynamic Parameters ───────────────────────────────────────
\begin{{frame}}{{Thermodynamic Parameters: {modifier}}}
  \begin{{columns}}[T]
    \begin{{column}}{{0.48\textwidth}}
      \small
      \setlength{{\tabcolsep}}{{6pt}}
      \renewcommand{{\arraystretch}}{{1.25}}
      \begin{{tabular}}{{lr}}
        \toprule
        \textbf{{Species}} & \textbf{{log K}} \\
        \midrule
{lk_rows}
        \bottomrule
      \end{{tabular}}
    \end{{column}}
    \begin{{column}}{{0.48\textwidth}}
      \small
      \begin{{itemize}}
        \setlength{{\itemsep}}{{4pt}}
        \item Database: sit.dat (SIT activity model)
        \item Modifier dose: 0.20 mol/kgw
        \item Temperature: 25$^\circ$C, I = 0 (NIST reference)
        \item Equilibrium phases: Gibbsite, Ferrihydrite(am), \\
              Cu(OH)$_2$(s), Co(OH)$_2$(s), Ni(OH)$_2$(s), MnOOH
        \item Fe complexation suppressed (kinetic)
        \item Scenarios: open / closed / partial CO$_2$
      \end{{itemize}}
    \end{{column}}
  \end{{columns}}
  \vspace{{4pt}}
  \begin{{beamercolorbox}}[rounded=true, shadow=false, wd=\textwidth]{{block body}}
    \tiny
    Source: NIST Standard Reference Database 46 Version 8.0. Values adjusted for ionic-strength effects at leachate conditions.
  \end{{beamercolorbox}}
\end{{frame}}

\end{{document}}
"""
    return tex


class BeamerAgent(BaseAgent):
    name = "BeamerAgent"

    def run(self, state: SimState) -> SimState:
        import shutil

        scorecard   = state.get("scorecard") or {}
        figure_path = state.get("figure_path") or ""
        sp_path     = state.get("species_contribution_path") or ""
        cfg         = state["run_config"]
        modifier    = state["modifier_name"]
        equiv_pts   = cfg["analyst"]["comparison_equiv"]
        exp_cfg     = cfg.get("experiment", {})
        phr_path    = Path(state.get("modifier_phr_path") or "")

        slug = phr_path.stem if phr_path.stem else "modifier"

        # ── Output folder structure ───────────────────────────────────────────
        # presentations/
        #   {slug}/
        #     figures/      ← PNG copies (xelatex finds them locally)
        #     {slug}_summary.tex
        #     {slug}_summary.pdf
        #     build/        ← aux, log, toc (kept out of root)
        pres_root  = Path("presentations")
        slide_dir  = pres_root / slug
        fig_dir    = slide_dir / "figures"
        build_dir  = slide_dir / "build"
        for d in (slide_dir, fig_dir, build_dir):
            d.mkdir(parents=True, exist_ok=True)

        # Copy figures into figures/ and record local names
        def _copy_fig(src: str) -> str:
            """Copy src PNG to figures/, return local relative path."""
            if not src:
                return ""
            p = Path(src)
            if not p.exists():
                return ""
            dest = fig_dir / p.name
            shutil.copy2(p, dest)
            return f"figures/{p.name}"

        fig_main_local = _copy_fig(figure_path)
        fig_sp_local   = _copy_fig(sp_path)

        complexes = _parse_complexes(phr_path)

        tex = _build_tex(modifier, slug, scorecard,
                         fig_main_local, fig_sp_local,
                         complexes, equiv_pts, exp_cfg, cfg)

        tex_name = f"{slug}_summary.tex"
        pdf_name = f"{slug}_summary.pdf"
        tex_path = slide_dir / tex_name
        pdf_path = slide_dir / pdf_name

        tex_path.write_text(tex, encoding="utf-8")
        print(f"[{self.name}] Written : {tex_path}")

        # Compile with xelatex (TeX Live compatible — no -aux-directory)
        try:
            for _ in range(2):
                subprocess.run(
                    ["xelatex", "-interaction=nonstopmode", tex_path.name],
                    cwd=str(slide_dir.resolve()),
                    capture_output=True, text=True, timeout=120,
                )
            # Move build artifacts to build/
            for ext in ("aux", "log", "toc", "nav", "out", "snm", "vrb"):
                art = slide_dir / f"{slug}_summary.{ext}"
                if art.exists():
                    shutil.move(str(art), str(build_dir / art.name))
            print(f"[{self.name}] Compiled: {pdf_path}")
        except FileNotFoundError:
            print(f"[{self.name}] xelatex not found — .tex written but not compiled.")
        except Exception as e:
            print(f"[{self.name}] Compilation error: {e}")

        print(f"[{self.name}] Folder  : {slide_dir}/")
        state["beamer_pdf"] = str(pdf_path)
        return state
